### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by leexk312** [Nicozwy/CofCED#1]
Hello! I'm looking for your code,when will you upload your code?

**Comment by Nicozwy** [comment]
Thank you for your attention. Codes will be uploaded after review and approval as soon as possible. 

It will be appreciated if you could  star this project.

**Comment by leexk312** [comment]
OK! Thanks for your reply.

**Comment by Nicozwy** [comment]
Hi, we have just uploaded all codes and datasets! @leexk312
