### ISSUE TITLE
How the final explanations are generated? They seem not to be a simple stack of the selected sentences

### ISSUE THREAD

**Issue by JunyiChE** [Nicozwy/CofCED#10]
Hi,
Very interesting and impressive work.  However, I wonder how the explanations are generated. 

Based on your code and description in your paper, it seems you selected the appropriate sentences based on the criteria.  Nevertheless, the selected sentences are not processed any further so it is more like a stack of the selected sentences.

However, from the content regarding case studies presented in your paper, the generated explanations seem to be some summarized facts with reasons and logic, which are not simple combinations of these sentences. 

Therefore, I wonder how the final explanations are generated? 

Don't know if I make the question clear, please tell me if I don't. Looking forward to your reply!

**Comment by Nicozwy** [comment]
Sorry for the late response.  The explanations in case studies denote the ground truth, and the final generated explanations were not further processed.
