### ISSUE TITLE
More details on how to run this code

### ISSUE THREAD

**Issue by lonelywolf1999** [Nicozwy/CofCED#3]
could you present a more detailed README about how to run this code?
Thank you very much !

**Comment by Nicozwy** [comment]
@lonelywolf1999 Download the datasets and put them into codes according to the guidance, and then run `python train_exp_fc5_xxx.py`.  We have updated the README. Could you star this project?

**Comment by lonelywolf1999** [comment]
Yeah, I see it.
I am all gratitude and will star this project immediately
