### ISSUE TITLE
A question about the training time and GPU

### ISSUE THREAD

**Issue by StephenHzj** [Nicozwy/CofCED#4]
Hi,

I tried to train the model on a  low-level GPU, like 2080Ti, but soon ran out of memory.

I want to ask some questions: what type of GPU is used for training? How many GPUs are used? How long did they train each time?

Thank you!

**Comment by Nicozwy** [comment]
Hi @StephenHzj， we suggest running this project on a Linux server with 24G GPU, e.g., 3090TI or RTX 6000. And the training time was not saved. By the way, could you star this project?

**Comment by StephenHzj** [comment]
Thanks for your reply.
