### ISSUE TITLE
vocab_article_source.json is not generated.

### ISSUE THREAD

**Issue by gauravkumar62024** [Nicozwy/CofCED#5]

**Comment by gauravkumar62024** [comment]
Dear sir, I was implementing your paper, but while implementing I got the error " vocab_article_source.json" not found. Could you please share the file vocab_article_source.json  as it is not generated during the implementation? @Nicozwy

**Comment by Nicozwy** [comment]
> Dear sir, I was implementing your paper, but while implementing I got the error " vocab_article_source.json" not found. Could you please share the file vocab_article_source.json as it is not generated during the implementation? @Nicozwy

Thank you for your attention. You can simply create a new file with the name " vocab_article_source.json" because it is not used in the codes.  Or you can modify the running file to run it.

**Comment by Aichiniuroumian** [comment]
> > Dear sir, I was implementing your paper, but while implementing I got the error " vocab_article_source.json" not found. Could you please share the file vocab_article_source.json as it is not generated during the implementation? @Nicozwy
> 
> Thank you for your attention. You can simply create a new file with the name " vocab_article_source.json" because it is not used in the codes. Or you can modify the running file to run it.

Hello, have you solved this problem?
I have followed the solution given by the author set "vocab_article_source=None" in "tran_xxx.py ", and I create a new file with the name "vocab_article_source.json", but when I run the program, it's empty when I parse the" vocab_article_source.json" file, Is there anything else that needs to be changed in the code?
Looking forward to your early reply, thank you very much! @Nicozwy @gauravkumar62024

**Comment by LYNBZ1018** [comment]
> > > Dear sir, I was implementing your paper, but while implementing I got the error " vocab_article_source.json" not found. Could you please share the file vocab_article_source.json as it is not generated during the implementation? @Nicozwy
> > 
> > 
> > Thank you for your attention. You can simply create a new file with the name " vocab_article_source.json" because it is not used in the codes. Or you can modify the running file to run it.
> 
> Hello, have you solved this problem? I have followed the solution given by the author set "vocab_article_source=None" in "tran_xxx.py ", and I create a new file with the name "vocab_article_source.json", but when I run the program, it's empty when I parse the" vocab_article_source.json" file, Is there anything else that needs to be changed in the code? Looking forward to your early reply, thank you very much! @Nicozwy @gauravkumar62024

Create a vocab_article_source.json file in the required path. To avoid the error of an empty file for everyone, write the following content that does not affect the program operation in the file. You can write randomly because this file will not be used.  

{
    "article_sources": [
        {
            "id": 1,
            "name": "Placeholder Source 1",
            "domain": "placeholder.com"
        },
        {
            "id": 2,
            "name": "Placeholder Source 2",
            "domain": "example.com"
        }
    ]
}
