### ISSUE TITLE
not found "vocab_article_source.json" error -> [Disable vocab_article_source]

### ISSUE THREAD

**Issue by gauravkumar62024** [Nicozwy/CofCED#6]
Hello @Nicozwy , I am trying to do this code snice 4 to 5 days but I am unable to understand that "vocab_article_source.json" file would be created by the code itself or this file exists in the dataset. If "vocab_article_source.json" file is part of existing part of data ,
Could you please provide me with the missing file as soon as possible so that I can continue testing and evaluating the code? Your prompt attention to this matter would be greatly appreciated.

Thank you for your time and effort in providing this code.

Sincerely,
Gaurav

![Screenshot 2023-01-19 143424](https://user-images.githubusercontent.com/78220135/213400158-7dfc8005-1304-4679-812f-1ebd058900b4.png)

**Comment by Nicozwy** [comment]
Hi @gauravkumar62024 , sorry for the delayed reply! You can set ``vocab_article_source=None" in "tran_xxx.py " because the file "vocab_article_source.json" is no longer used. 

For convenience, I will update the running file.

**Comment by gauravkumar62024** [comment]
Thanks for your response, I got it.
